<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'HtTemplateResolverModule\Exception\ExceptionInterface'              => __DIR__ . '/src/Exception/ExceptionInterface.php',
  'HtTemplateResolverModule\Exception\RuntimeException'                => __DIR__ . '/src/Exception/RuntimeException.php',
  'HtTemplateResolverModule\Factory\ViewResolverFactory'               => __DIR__ . '/src/Factory/ViewResolverFactory.php',
  'HtTemplateResolverModule\Factory\ViewResolversPluginManagerFactory' => __DIR__ . '/src/Factory/ViewResolversPluginManagerFactory.php',
  'HtTemplateResolverModule\Module'                                    => __DIR__ . '/src/Module.php',
  'HtTemplateResolverModule\View\Resolver\Factory\MapFactory'          => __DIR__ . '/src/View/Resolver/Factory/MapFactory.php',
  'HtTemplateResolverModule\View\Resolver\Factory\PathStackFactory'    => __DIR__ . '/src/View/Resolver/Factory/PathStackFactory.php',
  'HtTemplateResolverModule\View\Resolver\ResolversPluginManager'      => __DIR__ . '/src/View/Resolver/ResolversPluginManager.php',
);
